### ISSUE TITLE
UMT file format, possibility of using obj 3D mesh as input

### ISSUE THREAD

**Issue by MINDoSOFT** [umityoruk/renal-segmentation#1]
Hello and thank you for sharing your code.

I am trying to use it for my thesis to extract a 3D model of an object from a 3D mesh of a room. I saw in your code that you use the following "run_grabcut3d input.umt mask.umt output.umt" to run the grabcut3d algorithm. My question is what are these umt format files? Is it possible to use an obj file of a 3D mesh of a room as input?

Thank you.

**Comment by umityoruk** [comment]
The "umt" files are just binary files to represent ndarrays of numpy. See `Umt::load()` function in umt.cpp file. It consists of a header section followed by the data section. Header starts with a number of dimensions "ndim" (4 bytes) followed by the actual dimensions "dim0, dim1, ..." (ndim * 4 bytes) followed by a new line char (1 byte). The rest of the file is the serialized image data (dim0 * dim1 * dim2 * ... * dimN * 1 byte unsigned integers). 

I'm not really familiar with obj files but the function `grabCut3d()` takes `std::vector<Mat>` as the input. So as long as you can convert your 3d images into this format (i.e. a series of 2d images) you should be able to use 3D grabcut algorithm shared here. `run_grabcut3d()` does this by taking the umt files and constructing `std::vector<Mat>` from them.

Hope this clarifies things a bit. Good luck on your thesis.
